locale/fr_FR/LC_MESSAGES/django.po

Reverts peeringdb/peeringdb#339
Translation in msgid instead of msgstr

Revert " Another batch of fr_FR translations"

---

locale/ja_JP/LC_MESSAGES/django.po
locale/ja_JP/LC_MESSAGES/djangojs.po

Could you please upload files on beta site?

Completed to translate django.po to Japanese

---

locale/ja_JP/LC_MESSAGES/django.po

I have checked Japanese page on beta page, and revised some words in po files.
I'd like you to upload po files again.
Thank you.

Please upload JP po files of second revision on beta page.

---

peeringdb_server/templates/site/login.html
peeringdb_server/views.py
tests/test_inet.py

Pr 482 534

---

peeringdb_server/data_views.py

fix locale issue introduced by upgrading to django-peeringdb 1.0.0

---

peeringdb_server/data_views.py

fix issue with bool_choice_str enum translations

---

peeringdb_server/admin.py
peeringdb_server/management/commands/pdb_migrate_ixlans.py

Fix 628 cp ixlan search

---

peeringdb_server/templates/site/view_facility_bottom.html

Drop "Local" from "Local Exchanges" #591

---

peeringdb_server/inet.py

ARIN-NONAUTH should be allowed as IRR source too

ARIN has split into ARIN + ARIN-NONAUTH

---

peeringdb_server/templates/admin/org_merge_tool.html

load i18n filter tags for org merge tool (#753)

---

peeringdb_server/admin.py
peeringdb_server/ixf.py
peeringdb_server/models.py
peeringdb_server/templates/site/view_network_ixf_suggestions.html
peeringdb_server/views.py
tests/data/ixf/views/import.json
tests/test_admin.py
tests/test_ixf_member_import_protocol.py
tests/test_ixf_member_views.py

fixes #798
fixes #809
fixes #811
fixes #812
fixes #816
fixes #817

Dotf fixes 3

---

docs/api/op_create.md
docs/api/op_list.md
docs/api/op_retrieve.md
peeringdb_server/admin.py
peeringdb_server/api_schema.py
peeringdb_server/deskpro.py
peeringdb_server/ixf.py
peeringdb_server/management/commands/pdb_api_test.py
peeringdb_server/management/commands/pdb_migrate_ixlans.py
peeringdb_server/migrations/0004_geocode_fields.py
peeringdb_server/migrations/0006_network_allow_ixp_update.py
peeringdb_server/migrations/0029_auto_20200401_1006.py
peeringdb_server/mock.py
peeringdb_server/models.py
peeringdb_server/org_admin_views.py
peeringdb_server/rest.py
peeringdb_server/serializers.py
peeringdb_server/signals.py
peeringdb_server/templates/account/email_confirm.html
peeringdb_server/templates/email/notify-org-admin-merge.txt
peeringdb_server/templates/email/notify-pdb-admin-asnauto-skipvq.txt
peeringdb_server/templates/email/notify-pdb-admin-user-affil.txt
peeringdb_server/templates/site/error.html
peeringdb_server/views.py
tests/test_admin.py

Fix typos1 conflicts resolved

---

peeringdb_server/management/commands/pdb_geo_normalize_existing.py
peeringdb_server/models.py

777 fix address1 issue

---

fixtures/initial_data.json
mainsite/settings/__init__.py
peeringdb_server/management/commands/pdb_fix_930_users.py
peeringdb_server/models.py
peeringdb_server/org_admin_views.py
peeringdb_server/views.py
tests/test_entity_view.py
tests/test_orgadmin.py

Fixes 20210205

---

peeringdb_server/data_views.py
peeringdb_server/templates/site/advanced-search-org-present.html
tests/test_data_views.py
tests/test_views.py

advanced search fixes

---

mainsite/settings/__init__.py
peeringdb_server/rest.py
peeringdb_server/search.py
peeringdb_server/search_indexes.py
peeringdb_server/static/site.css
peeringdb_server/templates/search/indexes/peeringdb_server/facility_text.txt
peeringdb_server/templates/search/indexes/peeringdb_server/internetexchange_text.txt
peeringdb_server/templates/search/indexes/peeringdb_server/ixlanprefix_text.txt
peeringdb_server/templates/search/indexes/peeringdb_server/network_text.txt
peeringdb_server/templates/search/indexes/peeringdb_server/networkixlan_text.txt
peeringdb_server/templates/search/indexes/peeringdb_server/organization_text.txt
peeringdb_server/templates/site/search_result.html
tests/test_search.py

search results page

---

peeringdb_server/search.py

Fix 23 search result order

---

Dockerfile
tests/test_views.py

Fix fallback captcha deps

---

peeringdb_server/templates/site/index.html

Add October 8th Survey link to the index page

Survey 20210923

---

peeringdb_server/templates/site/notification_banner.html

remove survey notifications

---

peeringdb_server/views.py

This PR is to address issue raised in https://github.com/peeringdb/peeringdb/issues/1177

Add Error handling on locale field update

---

peeringdb_server/static/20c/twentyc.core.js

twentyc.core.js to latest

---

peeringdb_server/static/20c/twentyc.edit.js
peeringdb_server/static/site.css
peeringdb_server/templates/site/advanced-search.html
peeringdb_server/templates/site/view_organization_tools.html

Support 202205 fixes 2

---

.github/workflows/tests.yml
Dockerfile
poetry.lock

Update image build to fix tests

---

peeringdb_server/oauth_views.py
peeringdb_server/views.py

- fixes issue when user is not logged in when the oauth authorization request is started
- use django resolve to match oauth authorize url
- fixes issue with retrieving max cookie age

Oauth bug fix

---

peeringdb_server/ixf.py
tests/data/json_members_list/ixf.member.null.vlan_list_and_if_list.json
tests/test_ixf_member_import_protocol.py

fix issue with ix-f feeds that have vlan_list or if_list set to null

---

mainsite/settings/__init__.py
peeringdb_server/templates/apidocs/redoc.html

Add missing allowed sources for scripts

---

.gitignore
Ctl/dev/docker-compose.yml

upgrade to mysql8

---

.github/workflows/build-container.yml

add ghcr container build

---

poetry.lock
pyproject.toml

pin django-two-factor-auth to 1.14 to avoid compatibility issues

---

peeringdb_server/management/commands/pdb_api_test.py
peeringdb_server/rest.py
peeringdb_server/serializers.py

Fix issues with carrier-facility approval

---

mainsite/settings/__init__.py

update default objects

---

mainsite/settings/__init__.py

Moved from deployed config to defaults.
Fixes #1298

Update prefix limits

---

peeringdb_server/client_adaptor/backend.py

add new object types

---

peeringdb_server/templates/site/footer.html

set samesite on google analytics cookies

---

peeringdb_server/templates/site/advanced-search.html
peeringdb_server/templatetags/util.py

add query string to page title in advanced search results #1281

Advanced search page title

---

peeringdb_server/static/peeringdb.js

Fix social media links turning into plain text for editor

---

peeringdb_server/documents.py

Fix v2 search indexing deleted items

---

peeringdb_server/management/commands/pdb_api_test.py
peeringdb_server/rest.py

Fix pending campus sync

---

in.whoisd
mainsite/settings/__init__.py
peeringdb_server/management/commands/pdb_whois.py

fixes issue with "Was able to ping Redis, using RedisCache" appearing in whois responses

use debug print

---

Ctl/dev/docker-compose.yml
peeringdb_server/search.py
peeringdb_server/templates/site/search_result.html
peeringdb_server/templates/site/view.html

#1476 fix search result exact match to top
#170 fix popup not working for normal users / guest users

Support 202311 fixes 2

---

peeringdb_server/deskpro.py
peeringdb_server/inet.py
peeringdb_server/management/commands/pdb_api_test.py
peeringdb_server/management/commands/pdb_rir_status.py
peeringdb_server/mock.py
peeringdb_server/serializers.py
peeringdb_server/signals.py
peeringdb_server/templates/email/notify-pdb-admin-rir-status.txt
peeringdb_server/verified_update/const.py
peeringdb_server/verified_update/views.py
tests/test_generate_test_data.py
tests/test_rir_status.py
tests/test_verified_update.py

Fixes some remaining issues with the rir status update job

Support 202311 fixes 3

---

docs/dev/modules.md
docs/dev/modules/admin_commandline_tools.py.md
docs/dev/modules/import_views.py.md
docs/dev/modules/ixf.py.md
docs/dev/modules/models.py.md
docs/dev/modules/rest.py.md
docs/dev/views.md
mainsite/settings/__init__.py
peeringdb_server/admin_commandline_tools.py
peeringdb_server/import_views.py
peeringdb_server/ixf.py
peeringdb_server/migrations/0040_ixf_member_data.py
peeringdb_server/migrations/0073_manual_ixf_import.py
peeringdb_server/migrations/0078_ix_add_error_ixf_import_status.py
peeringdb_server/models.py
peeringdb_server/rest.py
peeringdb_server/static/api-schema.yaml
peeringdb_server/static/peeringdb.js
peeringdb_server/templates/email/notify-ixf-remote-changes.txt
peeringdb_server/templates/site/view_exchange_bottom.html
peeringdb_server/templates/site/view_network_bottom.html
tests/test_admin.py
tests/test_ixf_member_import_protocol.py
tests/test_ixf_member_views.py
tests/test_validators.py

Hope to clear out #1231 labeled as Good first issue and Time:Quick

#1231 IX-F consistency

---

peeringdb_server/api_cache.py
peeringdb_server/rest.py
peeringdb_server/templates/site/view.html
tests/test_api_cache.py

- addresses issue where normalized location search via the api would serve a cache response
- reverses button order in the new export data modal

Support 202406 fixes

---

mainsite/settings/__init__.py
src/peeringdb_server/templates/two_factor/core/login.html
src/peeringdb_server/templatetags/pdb_two_factor_ext.py
src/peeringdb_server/views.py

Fixes compatibility issues after two-factor library upgrade, causing issues with emailing one time passwords.
fixes #1309

Fix otp email one time password

---

src/peeringdb_server/search.py

fix anon user search autocomplete error

---

src/peeringdb_server/ixf.py

catch and log errors in the ix-f log during fetch, sanitize and parse
